### ISSUE TITLE
Compiling on openbsd fails

### ISSUE THREAD

**Issue by egtann** [awnumar/memcall#1]
Using go1.13

```
$ go get github.com/awnumar/memcall
memcall_openbsd.go:34:95: undefined: unix.MAP_CONCEAL
```

**Comment by awnumar** [comment]
The flag is [supported](https://man.openbsd.org/mmap.2#MAP_CONCEAL) by OpenBSD and it's defined in the standard library:

https://github.com/golang/sys/blob/2aa67d56cdd77167a5fb51358e8c3ce04bad68bb/unix/zerrors_openbsd_arm64.go#L927

Try running `go get -u ./...`?

**Comment by awnumar** [comment]
What architecture are you running?

**Comment by egtann** [comment]
I'm on `amd64`, but I am running `-current` so perhaps that has something to do with it? `go get -u ./...` throws the same error sadly.

**Comment by awnumar** [comment]
Defined the flag locally so the build should work now.

**Comment by egtann** [comment]
Thank you!
