### ISSUE TITLE
[]byte & GC

### ISSUE THREAD

**Issue by caleb-letsgo** [awnumar/memcall#5]
Is the []byte applied in the library(Alloc & Free) affected by the automatic go language recycling mechanism (GC) ?

**Comment by awnumar** [comment]
No, memory is allocated outside of the go heap.

**Comment by caleb-letsgo** [comment]
That is to say, the memory request is similar to the C language memory request and release, the request is from the system, the release is also directly returned to the system, right?

**Comment by awnumar** [comment]
On UNIX, memory is allocated and freed with the systemcalls mmap and munmap.

In Windows we use VirtualAlloc and VirtualFree.

**Comment by caleb-letsgo** [comment]
ok, thanks
